<?php
/**
 * Created by PhpStorm.
 * User: runs
 * Date: 19-1-28
 * Time: 下午5:42
 */

namespace EasySwoole\Smtp\Message;


use EasySwoole\Smtp\MessageHandler;

class Html extends MimeMessageBaseBean
{
    protected function initialize(): void
    {
        parent::initialize();
        $this->contentType = $this->contentType ?? 'text/html';
    }

    public function setBody($body): void
    {
        parent::setBody($body); // TODO: Change the autogenerated stub
        $this->contentTransferEncoding = MessageHandler::getContentTransferEncoding($body);
    }
}